---
- name: Install PHP
  apt: name={{ item }} state=present
  with_items:
    - php7.0-cli
    - php7.0-pgsql
    - php7.0-json
    - php7.0-curl
    - php7.0-gd
    - php7.0-imap
    - php7.0-intl
    - php7.0-dev

- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer

- name: Upload php.ini for CLI
  template: src=templates/php_cli.ini.j2 dest=/etc/php/7.0/cli/php.ini mode=640
