---
- name: Install ufw
  apt: name=ufw state=present

- name: Install fail2ban
  apt: name=fail2ban state=present

- name: Install unattended-upgrades
  apt: name=unattended-upgrades state=present

- name: Clone letsencrypt repository
  git: repo=https://github.com/letsencrypt/letsencrypt.git dest=/root/letsencrypt update=no
  notify:
    - Require letsencrypt certificate
