---
- name: Install postgreSQL
  apt: name={{ item }} state=present
  with_items:
    - libpq-dev
    - python-psycopg2
    - postgresql-9.4
    - postgresql-contrib-9.4
    - postgresql-9.4-postgis-2.1
