---
- name: Install Node.js
  apt: name=nodejs state=present

- name: Install NPM
  npm: name=npm global=yes version=3.3.9 state=present

- name: Install Aglio globally
  npm: global=yes name=aglio production=yes state=present
