---
- name: Install nginx
  apt: name=nginx state=present

- name: Install PHP-FPM
  apt: name=php7.0-fpm state=present

- name: Upload php.ini file
  template: src=templates/php_fpm.ini.j2 dest=/etc/php/7.0/fpm/php.ini mode=640

- name: Upload fastcgi_params file
  template: src=templates/fastcgi_params.j2 dest=/etc/nginx/fastcgi_params mode=640

- name: Upload nginx.conf file
  template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=640
  notify:
    - Restart nginx

- name: Upload www.conf file
  template: src=templates/www.conf.j2 dest=/etc/php/7.0/fpm/pool.d/www.conf mode=640

- name: List vagrant user groups
  shell: groups vagrant
  changed_when: False
  register: vagrant_groups

- name: Add the vagrant user to the www-data group
  when: "not 'www-data' in vagrant_groups.stdout"
  shell: usermod -a -G www-data vagrant
