---
- name: Install common software
  apt: name=software-properties-common state=present

- name: Add nginx repository
  apt_repository: repo='ppa:nginx/stable' state=present

- name: Add PHP repository
  apt_repository: repo='ppa:ondrej/php5-5.6' state=present

- name: Add NodeSource GPG key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: Add Node.js repository
  apt_repository: repo='deb https://deb.nodesource.com/node_0.12 {{ ansible_distribution_release }} main' state=present

- name: Add PostgreSQL apt key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present

- name: Add PostgreSQL repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main' state=present

- name: Update package lists
  when: apt_update
  apt: update_cache=yes cache_valid_time={{ apt_update_cache_time_in_seconds }}

- name: Upgrade packages
  when: apt_update
  apt: upgrade=full force=yes
