---
- name: Add GitHub to vagrant known hosts
  lineinfile:
    dest: ~vagrant/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
    state: present

- name: Add .composer directory for vagrant
  file: path=~vagrant/.composer state=directory group=vagrant owner=vagrant mode=775

- name: Add GitHub access token to Composer config
  template: src=composer_auth.json.j2 dest=~vagrant/.composer/auth.json group=vagrant owner=vagrant

- name: Upload RSA public key for GitHub
  template: src=github_id_rsa.pub.j2 dest=~vagrant/.ssh/github_id_rsa.pub group=vagrant owner=vagrant mode=644

- name: Upload encrypted RSA private key for GitHub
  copy: src=github_id_rsa.enc dest=~vagrant/.ssh/github_id_rsa.enc group=vagrant owner=vagrant mode=600
  register: github_rsa_private

- name: Decrypt RSA private key for GitHub
  shell: openssl enc -aes-256-cbc -salt -d -in ~vagrant/.ssh/github_id_rsa.enc -out ~vagrant/.ssh/github_id_rsa -k {{ secrets_password }}; chmod 600 ~vagrant/.ssh/github_id_rsa
  when: github_rsa_private.changed
  sudo: yes
  sudo_user: vagrant

- name: Upload vagrant ssh config
  template: src=vagrant_ssh_config.j2 dest=~vagrant/.ssh/config group=vagrant owner=vagrant mode=640
  notify: Restart ssh
