---
- name: Start supervisor
  service: name=supervisor state=started

- name: Create directory for supervisor logs
  file: path=/var/log/queues state=directory

- name: Upload queues config
  template: src=templates/queues.j2 dest=/etc/supervisor/conf.d/queues.conf mode=640
  notify: Restart groupeat queues
