---
- name: Create nginx SSL directory
  when: ssl_enabled
  file: path=/etc/nginx/ssl state=directory

- name: Upload encrypted nginx SSL certificate
  when: ssl_enabled
  copy: src=nginx.crt.enc dest=/etc/nginx/ssl/nginx.crt.enc mode=640
  register: nginx_certificate

- name: Decrypt nginx SSL certificate
  when: nginx_certificate.changed
  shell: openssl enc -aes-256-cbc -salt -d -in /etc/nginx/ssl/nginx.crt.enc -out /etc/nginx/ssl/nginx.crt -k {{ secrets_password }}; chmod 640 /etc/nginx/ssl/nginx.crt

- name: Upload encrypted nginx SSL private key
  when: ssl_enabled
  copy: src=nginx.key.enc dest=/etc/nginx/ssl/nginx.key.enc mode=640
  register: nginx_private_key

- name: Decrypt nginx SSL private key
  when: nginx_private_key.changed
  shell: openssl enc -aes-256-cbc -salt -d -in /etc/nginx/ssl/nginx.key.enc -out /etc/nginx/ssl/nginx.key -k {{ secrets_password }}; chmod 640 /etc/nginx/ssl/nginx.key
