---
- name: Upload SSH daemon config
  template: src=templates/sshd_config.j2 dest=/etc/ssh/sshd_config
  notify: Restart ssh

- name: Upload APT update config
  template: src=templates/apt_periodic.j2 dest=/etc/apt/apt.conf.d/02periodic

- name: Upload unattended updates config
  template: src=templates/unattended_upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades

- name: Setup ufw to deny incoming packages by default
  ufw: state=enabled policy=deny direction=incoming

- name: Setup ufw to allow outgoing packages by default
  ufw: state=enabled policy=allow direction=outgoing

- name: Allow SSH traffic
  ufw: rule=allow port=22 proto=tcp

- name: Allow HTTP traffic
  ufw: rule=allow port=80 proto=tcp

- name: Allow HTTPS traffic
  ufw: rule=allow port=443 proto=tcp

- name: Allow PostgreSQL external connection
  ufw: rule=allow port=5432 proto=tcp

- name: Allow APNS inbound traffic
  ufw: rule=allow port=2195 proto=tcp

- name: Allow APNS feedback inbound traffic
  ufw: rule=allow port=2196 proto=tcp

- name: Allow Socket.IO traffic
  ufw: rule=allow port=3000 proto=tcp

- name: Allow SqlPad traffic
  ufw: rule=allow port=8000 proto=tcp
