---
- name: Check if API is already deployed
  stat: path=~vagrant/api
  register: api

- name: Setup API
  when: api.stat.exists == false
  local_action: shell cd ../groupeat-api; rocketeer setup --on={{ env }}
  sudo: false

- name: Deploy API
  when: api.stat.exists == false
  local_action: shell cd ../groupeat-api; rocketeer deploy --on={{ env }} --branch={{ env }}
  sudo: false

- name: Run migrations
  when: api.stat.exists == false
  shell: php artisan migrate --seed --force
  args:
    chdir: ~vagrant/api/current
  sudo: true
  sudo_user: vagrant

- name: Check if Web App is already deployed
  stat: path=~vagrant/app
  register: webApp

- name: Deploy Web App
  when: webApp.stat.exists == false
  local_action: shell cd ../groupeat-web-app; ./node_modules/.bin/gulp deploy --{{ env }}
  sudo: false

- name: Check if Showcase is already deployed
  stat: path=~vagrant/showcase
  register: showcase

- name: Deploy Showcase
  when: showcase.stat.exists == false
  local_action: shell cd ../groupeat-showcase; ./node_modules/.bin/shipit {{ env }} deploy
  sudo: false
