---
- name: Check if API is already deployed
  stat: path=~vagrant/api
  register: api

- name: Setup API
  when: api.stat.exists == false
  local_action: shell cd ../groupeat-api; rocketeer setup --on={{ env }}
  sudo: false

- name: Deploy API
  when: api.stat.exists == false
  local_action: shell cd ../groupeat-api; rocketeer deploy --on={{ env }} --branch={{ env }}
  sudo: false

- name: Run migrations
  when: api.stat.exists == false
  shell: php artisan migrate --seed --force
  args:
    chdir: ~vagrant/api/current
  sudo: true
  sudo_user: vagrant

- name: Check if frontend is already deployed
  stat: path=~vagrant/frontend
  register: frontend

- name: Deploy frontend
  when: frontend.stat.exists == false
  local_action: shell cd ../groupeat-frontend; gulp deploy --{{ env }}
  sudo: false
