---
- name: Upload Laravel .env file
  template: src=templates/env.{{ 'local' if (env == 'dev') else 'distant' }}.j2 dest=~vagrant/.env group=vagrant owner=vagrant mode=640
  notify: Recache Laravel config
