---
- name: Create groupeat PostgreSQL database
  postgresql_db: name=groupeat state=present
  sudo: yes
  sudo_user: postgres

- name: Create groupeat user and grant him access to the db
  postgresql_user: db=groupeat name=groupeat password={{ staging_pgsql_password if app_env == 'staging' else (production_pgsql_password if app_env == 'production' else 'groupeat') }} state=present role_attr_flags=SUPERUSER,INHERIT,NOCREATEDB,NOCREATEROLE,NOREPLICATION
  notify: Restart postgresql
  sudo: yes
  sudo_user: postgres
