---
- name: Upload encrypted APNS certificate
  copy: src=APNS.pem.enc dest=~vagrant/APNS.pem.enc group=vagrant owner=vagrant mode=640
  register: apns_certificate

- name: Decrypt APNS certificate
  when: apns_certificate.changed
  shell: openssl enc -aes-256-cbc -salt -d -in ~vagrant/APNS.pem.enc -out ~vagrant/APNS.pem -k {{ secrets_password }}; chmod 640 ~vagrant/APNS.pem
  sudo: yes
  sudo_user: vagrant
