---
- name: Upload GroupEat site config
  template: src=templates/{{ inventory_hostname }}.nginx.conf.j2 dest=/etc/nginx/sites-available/groupeat
  notify:
    - Restart nginx

- name: Enable GroupEat site
  file: src=/etc/nginx/sites-available/groupeat dest=/etc/nginx/sites-enabled/groupeat state=link
  notify:
    - Restart nginx
