---
- name: Upload encrypted APNS certificate
  copy: src={{ env }}.apns.pem.enc dest=~vagrant/.apns.pem.enc group=vagrant owner=vagrant mode=640
  register: apns_certificate

- name: Decrypt APNS certificate
  when: apns_certificate.changed
  shell: openssl enc -aes-256-cbc -salt -d -in ~vagrant/.apns.pem.enc -out ~vagrant/.apns.pem -k {{ secrets_password }}; chmod 640 ~vagrant/.apns.pem
  sudo: yes
  sudo_user: vagrant
