---
- name: Restart sysctl
  command: sysctl -p

- name: Restart nginx
  service: name=nginx state=restarted

- name: Restart queues
  service: name=supervisor state=restarted

- name: Restart rsyslog
  service: name=rsyslog state=restarted

- name: Restart postgresql
  service: name=postgresql state=restarted

- name: Restart ssh
  service: name=ssh state=restarted
  notify: Add ssh missing keys

- name: Reconfigure timezone
  shell: dpkg-reconfigure --frontend noninteractive tzdata

- name: Add ssh missing keys
  shell: ssh-keygen -A

- name: Recache Laravel config
  shell: php /home/vagrant/api/current/artisan config:cache
  sudo: yes
  sudo_user: vagrant

- name: Require letsencrypt certificate
  shell: /root/letsencrypt/letsencrypt-auto certonly --standalone --redirect --duplicate --text --email tib.dex@gmail.com --agree-tos -d groupeat.fr -d www.groupeat.fr -d api.groupeat.fr -d app.groupeat.fr -d analytics.groupeat.fr -d restaurant.groupeat.fr -d blog.groupeat.fr -d docs.groupeat.fr
